// Generated by CoffeeScript 1.7.1

module.exports = {
  development: {
    replicaset: 'ballsir',
    domain: '127.0.0.01',
    port: 27017,
    user: '',
    pwd: '',
    poolSize: 100,
    database: 'ballsir'
  },
  production: {
    replicaset: 'ballsir',
    // domain: 'pet.cms.lan',
    domain: '127.0.0.1',
    port: 27017,
    user: 'jb-pet',
    pwd: '3e*_raGtr_256^0',
    poolSize: 100,
    database: 'ballsir'
  }
};

