// Generated by CoffeeScript 1.7.1
(function() {
  var ObjectID, mongodb;

  mongodb = require('../dao/mongodb');

  ObjectID = require('mongodb').ObjectID;

  module.exports = {
    increment: function(callback) {
      var query, queryDevelopment, queryProduction;
      queryProduction = {
        _id: ObjectID("5423bb70044e982193f16a0f")
      };
      queryDevelopment = {
        _id: ObjectID("5403e5ee65414c3bea7050ab")
      };
      query = process.env['NODE_ENV'] === "production" ? queryProduction : queryDevelopment;
      return mongodb.findAndModify('maxkey', query, {
        $inc: {
          key: 1
        }
      }, {
        "new": true
      }, function(err, result) {
        return callback(err, result.key);
      });
    }
  };

}).call(this);
