// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    fourRandom: function() {
      var a;
      a = Math.round(Math.random() * 8999) + 1000;
      return a;
    }
  };

}).call(this);
