// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    getToday: function() {
      var currentDate, day, month, myDate, year;
      myDate = new Date();
      year = myDate.getFullYear();
      month = myDate.getMonth() + 1;
      day = myDate.getDate();
      month = month < 10 ? "0" + month : month;
      day = day < 10 ? "0" + day : day;
      currentDate = year + "-" + month + "-" + day;
      return currentDate;
    },
    getYesterday: function() {
      var currentDate, day, month, myDate, year;
      myDate = new Date();
      myDate.setDate(myDate.getDate() - 1);
      year = myDate.getFullYear();
      month = myDate.getMonth() + 1;
      day = myDate.getDate();
      month = month < 10 ? "0" + month : month;
      day = day < 10 ? "0" + day : day;
      currentDate = year + "-" + month + "-" + day;
      return currentDate;
    },
    getUniqueNum: function() {
      var day, hour, millSecond, minute, month, myDate, second, uniqueNum, year;
      myDate = new Date();
      year = myDate.getFullYear();
      month = myDate.getMonth() + 1;
      day = myDate.getDate();
      hour = myDate.getHours();
      minute = myDate.getMinutes();
      second = myDate.getSeconds();
      millSecond = myDate.getMilliseconds();
      month = month < 10 ? "0" + month : month;
      day = day < 10 ? "0" + day : day;
      hour = hour < 10 ? "0" + hour : hour;
      minute = minute < 10 ? "0" + minute : minute;
      second = second < 10 ? "0" + second : second;
      millSecond = millSecond < 100 ? (millSecond < 10 ? "00" + millSecond : "0" + millSecond) : millSecond;
      uniqueNum = year + month + day + hour + minute + second + millSecond;
      return uniqueNum;
    },
    getWeekAgoDate: function() {
      var getWeekAgo, occur, tday, tmonth, tyear, weekAgo;
      occur = new Date();
      weekAgo = new Date(occur.getTime() - 1000 * 60 * 60 * 24 * 7);
      tyear = weekAgo.getFullYear();
      tmonth = weekAgo.getMonth() + 1;
      tday = weekAgo.getDate();
      tday = tday < 10 ? "0" + tday : tday;
      tmonth = tmonth < 10 ? "0" + tmonth : tmonth;
      getWeekAgo = tyear + "-" + tmonth + "-" + tday;
      return getWeekAgo;
    },
    getNow: function() {
      var mydate;
      mydate = new Date();
      return mydate;
    },
    getDateInCommon: function() {
      var Occurence, day, hour, millSecond, minute, month, myDate, second, year;
      myDate = new Date();
      year = myDate.getFullYear();
      month = myDate.getMonth() + 1;
      day = myDate.getDate();
      hour = myDate.getHours();
      minute = myDate.getMinutes();
      second = myDate.getSeconds();
      millSecond = myDate.getMilliseconds();
      month = month < 10 ? "0" + month : month;
      day = day < 10 ? "0" + day : day;
      hour = hour < 10 ? "0" + hour : hour;
      minute = minute < 10 ? "0" + minute : minute;
      second = second < 10 ? "0" + second : second;
      Occurence = year + "-" + month + "-" + day + " " + hour + ":" + minute + ":" + second;
      return Occurence;
    },
    getYearsOld: function(birthdate) {
      var date1, date2, date3, days, monthsold, yearsold;
      date1 = new Date(birthdate);
      date2 = new Date();
      date3 = date2.getTime() - date1.getTime();
      days = Math.floor(date3 / (24 * 3600 * 1000));
      monthsold = parseInt(days / 30);
      yearsold = parseInt(monthsold / 12);
      if (yearsold > 0) {
        return "" + yearsold + "岁";
      }
      if (monthsold > 0) {
        return "" + monthsold + "个月";
      }
      return "" + days + "天";
    },
    getTimeLine: function(timeArray) {
      var date, dateArray, index, time, uniqArray, _i, _j, _len, _len1;
      dateArray = [];
      for (_i = 0, _len = timeArray.length; _i < _len; _i++) {
        time = timeArray[_i];
        index = time['time'].indexOf(" ");
        date = time['time'].substring(0, index);
        dateArray.push(date);
      }
      uniqArray = [];
      for (_j = 0, _len1 = dateArray.length; _j < _len1; _j++) {
        date = dateArray[_j];
        if (uniqArray.indexOf(date) === -1) {
          uniqArray.push(date);
        }
      }
      return uniqArray;
    }
  };

}).call(this);
